export const ProjectModel = {
  id: null,
  project_name: "",
  friendly_name: "",
  client_id: null,
  project_manager: null,
  sales_person: null,
  client_contact_id: null,
  country: "",
  cpi: 0,
  ir: 0,
  loi: 0,
  award_points: 0,
  survey_link: "",
  test_link: "",
  parent_project: "",
  req_completes: 0,
  max_completes: 0,
  notes: "",
  use_test_link: false,
  use_prescreener: false,
  status: "ACTIVE",
  created_at: null,
};